### PR TITLE
✍️ typo-fixed

### PR DESCRIPTION
**Pull request by nitinmewar**

### CODE REVIEW

**Comment by nitinmewar** [comment]
@acollign @joerghoh can you please review this.

**Comment by acollign** [comment]
Ok with the typo fix, yet I have no idea about the claim. You would need to ask some PDF guy.

**Review by joerghoh — APPROVED** [review]

**Comment by aheim0** [comment]
Thank you for reporting this. We will fix it.

**Comment by aheim0** [comment]
Tracked with CQDOC-19630

**Comment by guillaumecarlino** [comment]
Typo fixed.

**Pull request closed without merging**
