### PR TITLE
Update introduction-forms-authoring.md

### PR DESCRIPTION
**Pull request by nehbansa**
Updated Component table - corrected the Component Column values for Footer and Header rows.

### CODE REVIEW

**Comment by nehbansa** [comment]
@adobe/open-source-office - I want to clarify whther I need to sign CLA as I am Adobe Employee

**Comment by anujkapo** [comment]
Thanks, @nehbansa. We will take care of the fix.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17266.

**Comment by nehbansa** [comment]
@anujkapo - Great, thank you!

**Pull request closed without merging**
