### PR TITLE
First paragraph remove extra irregular verb

### PR DESCRIPTION
**Pull request by malaradobe**
The old paragraph had an extra irregular verb "... need to be be cleaned ..." and I just made some updates while I was ad it fixing it.

### CODE REVIEW

**Comment by malaradobe** [comment]
I have signed the Adobe CLA

**Comment by aheim0** [comment]
Thanks for raising this, we will review.

**Comment by aheim0** [comment]
Tracked with CQDOC-20179

**Comment by aheim0** [comment]
Thanks for raising this. Changes have been applied directly and will be published soon.
Closing this.

**Pull request closed without merging**
