### PR TITLE
Added link for JAVA API Best Practices page

### PR DESCRIPTION
**Pull request by himanshu-pathak**
Added link for JAVA API Best Practices page

### CODE REVIEW

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @himanshu-pathak and for the review @davidjgonzalez. We'll get these changes integrated.

**Comment by bohnertchris** [comment]
CQDOC-15638

**Comment by bohnertchris** [comment]
@himanshu-pathak can you please clarify what the link is supposed to point to? The path provided does not exist.

**Comment by bohnertchris** [comment]
@himanshu-pathak can you please comment? I can not find the link you specified.

**Comment by himanshu-pathak** [comment]
The fully qualified link is https://docs.adobe.com/content/help/en/experience-manager-learn/foundation/development/understand-java-api-best-practices.html

**Comment by bohnertchris** [comment]
Thank you for providing the link and making the suggestion, @himanshu-pathak . The change is in commit a252ef6 in this repository and in commit 1bfc4d7 in 6.4.

**Pull request closed without merging**
