### PR TITLE
Update deprecated-removed-features.md

### PR DESCRIPTION
**Pull request by brendan-walsh**
Fixed typo

### CODE REVIEW

**Comment by ashishguptaiitb** [comment]
Thank you @brendan-walsh  for sharing.
I've updated this in our release notes.

**Comment by brendan-walsh** [comment]
Sounds good @ashishguptaiitb, should I just go ahead and close this PR then?

**Comment by ashishguptaiitb** [comment]
Feel free to either close it right away or do so when the changes get published live in a few hours. This and more typo fixes are in the repo and only a matter of time before the build churns out and all updates are published.

**Comment by ashishguptaiitb** [comment]
I just checked that the updated pages are published and available online. The typos are fixed. Please close this PR @brendan-walsh

**Comment by brendan-walsh** [comment]
This is no longer relevant.  Closing.

**Pull request closed without merging**
